/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package climate.schema;

import org.apache.commons.lang.builder.HashCodeBuilder;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ModisPixelLocation implements org.apache.thrift.TBase<ModisPixelLocation, ModisPixelLocation._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ModisPixelLocation");

  private static final org.apache.thrift.protocol.TField RESOLUTION_FIELD_DESC = new org.apache.thrift.protocol.TField("resolution", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField TILE_H_FIELD_DESC = new org.apache.thrift.protocol.TField("tileH", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField TILE_V_FIELD_DESC = new org.apache.thrift.protocol.TField("tileV", org.apache.thrift.protocol.TType.I32, (short)3);
  private static final org.apache.thrift.protocol.TField SAMPLE_FIELD_DESC = new org.apache.thrift.protocol.TField("sample", org.apache.thrift.protocol.TType.I32, (short)4);
  private static final org.apache.thrift.protocol.TField LINE_FIELD_DESC = new org.apache.thrift.protocol.TField("line", org.apache.thrift.protocol.TType.I32, (short)5);

  public String resolution;
  public int tileH;
  public int tileV;
  public int sample;
  public int line;

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    RESOLUTION((short)1, "resolution"),
    TILE_H((short)2, "tileH"),
    TILE_V((short)3, "tileV"),
    SAMPLE((short)4, "sample"),
    LINE((short)5, "line");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // RESOLUTION
          return RESOLUTION;
        case 2: // TILE_H
          return TILE_H;
        case 3: // TILE_V
          return TILE_V;
        case 4: // SAMPLE
          return SAMPLE;
        case 5: // LINE
          return LINE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __TILEH_ISSET_ID = 0;
  private static final int __TILEV_ISSET_ID = 1;
  private static final int __SAMPLE_ISSET_ID = 2;
  private static final int __LINE_ISSET_ID = 3;
  private BitSet __isset_bit_vector = new BitSet(4);

  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.RESOLUTION, new org.apache.thrift.meta_data.FieldMetaData("resolution", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.TILE_H, new org.apache.thrift.meta_data.FieldMetaData("tileH", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.TILE_V, new org.apache.thrift.meta_data.FieldMetaData("tileV", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.SAMPLE, new org.apache.thrift.meta_data.FieldMetaData("sample", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.LINE, new org.apache.thrift.meta_data.FieldMetaData("line", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ModisPixelLocation.class, metaDataMap);
  }

  public ModisPixelLocation() {
  }

  public ModisPixelLocation(
    String resolution,
    int tileH,
    int tileV,
    int sample,
    int line)
  {
    this();
    this.resolution = resolution;
    this.tileH = tileH;
    setTileHIsSet(true);
    this.tileV = tileV;
    setTileVIsSet(true);
    this.sample = sample;
    setSampleIsSet(true);
    this.line = line;
    setLineIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ModisPixelLocation(ModisPixelLocation other) {
    __isset_bit_vector.clear();
    __isset_bit_vector.or(other.__isset_bit_vector);
    if (other.isSetResolution()) {
      this.resolution = other.resolution;
    }
    this.tileH = other.tileH;
    this.tileV = other.tileV;
    this.sample = other.sample;
    this.line = other.line;
  }

  public ModisPixelLocation deepCopy() {
    return new ModisPixelLocation(this);
  }

  @Override
  public void clear() {
    this.resolution = null;
    setTileHIsSet(false);
    this.tileH = 0;
    setTileVIsSet(false);
    this.tileV = 0;
    setSampleIsSet(false);
    this.sample = 0;
    setLineIsSet(false);
    this.line = 0;
  }

  public String getResolution() {
    return this.resolution;
  }

  public ModisPixelLocation setResolution(String resolution) {
    this.resolution = resolution;
    return this;
  }

  public void unsetResolution() {
    this.resolution = null;
  }

  /** Returns true if field resolution is set (has been assigned a value) and false otherwise */
  public boolean isSetResolution() {
    return this.resolution != null;
  }

  public void setResolutionIsSet(boolean value) {
    if (!value) {
      this.resolution = null;
    }
  }

  public int getTileH() {
    return this.tileH;
  }

  public ModisPixelLocation setTileH(int tileH) {
    this.tileH = tileH;
    setTileHIsSet(true);
    return this;
  }

  public void unsetTileH() {
    __isset_bit_vector.clear(__TILEH_ISSET_ID);
  }

  /** Returns true if field tileH is set (has been assigned a value) and false otherwise */
  public boolean isSetTileH() {
    return __isset_bit_vector.get(__TILEH_ISSET_ID);
  }

  public void setTileHIsSet(boolean value) {
    __isset_bit_vector.set(__TILEH_ISSET_ID, value);
  }

  public int getTileV() {
    return this.tileV;
  }

  public ModisPixelLocation setTileV(int tileV) {
    this.tileV = tileV;
    setTileVIsSet(true);
    return this;
  }

  public void unsetTileV() {
    __isset_bit_vector.clear(__TILEV_ISSET_ID);
  }

  /** Returns true if field tileV is set (has been assigned a value) and false otherwise */
  public boolean isSetTileV() {
    return __isset_bit_vector.get(__TILEV_ISSET_ID);
  }

  public void setTileVIsSet(boolean value) {
    __isset_bit_vector.set(__TILEV_ISSET_ID, value);
  }

  public int getSample() {
    return this.sample;
  }

  public ModisPixelLocation setSample(int sample) {
    this.sample = sample;
    setSampleIsSet(true);
    return this;
  }

  public void unsetSample() {
    __isset_bit_vector.clear(__SAMPLE_ISSET_ID);
  }

  /** Returns true if field sample is set (has been assigned a value) and false otherwise */
  public boolean isSetSample() {
    return __isset_bit_vector.get(__SAMPLE_ISSET_ID);
  }

  public void setSampleIsSet(boolean value) {
    __isset_bit_vector.set(__SAMPLE_ISSET_ID, value);
  }

  public int getLine() {
    return this.line;
  }

  public ModisPixelLocation setLine(int line) {
    this.line = line;
    setLineIsSet(true);
    return this;
  }

  public void unsetLine() {
    __isset_bit_vector.clear(__LINE_ISSET_ID);
  }

  /** Returns true if field line is set (has been assigned a value) and false otherwise */
  public boolean isSetLine() {
    return __isset_bit_vector.get(__LINE_ISSET_ID);
  }

  public void setLineIsSet(boolean value) {
    __isset_bit_vector.set(__LINE_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case RESOLUTION:
      if (value == null) {
        unsetResolution();
      } else {
        setResolution((String)value);
      }
      break;

    case TILE_H:
      if (value == null) {
        unsetTileH();
      } else {
        setTileH((Integer)value);
      }
      break;

    case TILE_V:
      if (value == null) {
        unsetTileV();
      } else {
        setTileV((Integer)value);
      }
      break;

    case SAMPLE:
      if (value == null) {
        unsetSample();
      } else {
        setSample((Integer)value);
      }
      break;

    case LINE:
      if (value == null) {
        unsetLine();
      } else {
        setLine((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case RESOLUTION:
      return getResolution();

    case TILE_H:
      return new Integer(getTileH());

    case TILE_V:
      return new Integer(getTileV());

    case SAMPLE:
      return new Integer(getSample());

    case LINE:
      return new Integer(getLine());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case RESOLUTION:
      return isSetResolution();
    case TILE_H:
      return isSetTileH();
    case TILE_V:
      return isSetTileV();
    case SAMPLE:
      return isSetSample();
    case LINE:
      return isSetLine();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof ModisPixelLocation)
      return this.equals((ModisPixelLocation)that);
    return false;
  }

  public boolean equals(ModisPixelLocation that) {
    if (that == null)
      return false;

    boolean this_present_resolution = true && this.isSetResolution();
    boolean that_present_resolution = true && that.isSetResolution();
    if (this_present_resolution || that_present_resolution) {
      if (!(this_present_resolution && that_present_resolution))
        return false;
      if (!this.resolution.equals(that.resolution))
        return false;
    }

    boolean this_present_tileH = true;
    boolean that_present_tileH = true;
    if (this_present_tileH || that_present_tileH) {
      if (!(this_present_tileH && that_present_tileH))
        return false;
      if (this.tileH != that.tileH)
        return false;
    }

    boolean this_present_tileV = true;
    boolean that_present_tileV = true;
    if (this_present_tileV || that_present_tileV) {
      if (!(this_present_tileV && that_present_tileV))
        return false;
      if (this.tileV != that.tileV)
        return false;
    }

    boolean this_present_sample = true;
    boolean that_present_sample = true;
    if (this_present_sample || that_present_sample) {
      if (!(this_present_sample && that_present_sample))
        return false;
      if (this.sample != that.sample)
        return false;
    }

    boolean this_present_line = true;
    boolean that_present_line = true;
    if (this_present_line || that_present_line) {
      if (!(this_present_line && that_present_line))
        return false;
      if (this.line != that.line)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    HashCodeBuilder builder = new HashCodeBuilder();

    boolean present_resolution = true && (isSetResolution());
    builder.append(present_resolution);
    if (present_resolution)
      builder.append(resolution);

    boolean present_tileH = true;
    builder.append(present_tileH);
    if (present_tileH)
      builder.append(tileH);

    boolean present_tileV = true;
    builder.append(present_tileV);
    if (present_tileV)
      builder.append(tileV);

    boolean present_sample = true;
    builder.append(present_sample);
    if (present_sample)
      builder.append(sample);

    boolean present_line = true;
    builder.append(present_line);
    if (present_line)
      builder.append(line);

    return builder.toHashCode();
  }

  public int compareTo(ModisPixelLocation other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    ModisPixelLocation typedOther = (ModisPixelLocation)other;

    lastComparison = Boolean.valueOf(isSetResolution()).compareTo(typedOther.isSetResolution());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetResolution()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.resolution, typedOther.resolution);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTileH()).compareTo(typedOther.isSetTileH());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTileH()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tileH, typedOther.tileH);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTileV()).compareTo(typedOther.isSetTileV());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTileV()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tileV, typedOther.tileV);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetSample()).compareTo(typedOther.isSetSample());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSample()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.sample, typedOther.sample);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLine()).compareTo(typedOther.isSetLine());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLine()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.line, typedOther.line);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    org.apache.thrift.protocol.TField field;
    iprot.readStructBegin();
    while (true)
    {
      field = iprot.readFieldBegin();
      if (field.type == org.apache.thrift.protocol.TType.STOP) { 
        break;
      }
      switch (field.id) {
        case 1: // RESOLUTION
          if (field.type == org.apache.thrift.protocol.TType.STRING) {
            this.resolution = iprot.readString();
          } else { 
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 2: // TILE_H
          if (field.type == org.apache.thrift.protocol.TType.I32) {
            this.tileH = iprot.readI32();
            setTileHIsSet(true);
          } else { 
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 3: // TILE_V
          if (field.type == org.apache.thrift.protocol.TType.I32) {
            this.tileV = iprot.readI32();
            setTileVIsSet(true);
          } else { 
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 4: // SAMPLE
          if (field.type == org.apache.thrift.protocol.TType.I32) {
            this.sample = iprot.readI32();
            setSampleIsSet(true);
          } else { 
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 5: // LINE
          if (field.type == org.apache.thrift.protocol.TType.I32) {
            this.line = iprot.readI32();
            setLineIsSet(true);
          } else { 
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();

    // check for required fields of primitive type, which can't be checked in the validate method
    validate();
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    validate();

    oprot.writeStructBegin(STRUCT_DESC);
    if (this.resolution != null) {
      oprot.writeFieldBegin(RESOLUTION_FIELD_DESC);
      oprot.writeString(this.resolution);
      oprot.writeFieldEnd();
    }
    oprot.writeFieldBegin(TILE_H_FIELD_DESC);
    oprot.writeI32(this.tileH);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(TILE_V_FIELD_DESC);
    oprot.writeI32(this.tileV);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(SAMPLE_FIELD_DESC);
    oprot.writeI32(this.sample);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(LINE_FIELD_DESC);
    oprot.writeI32(this.line);
    oprot.writeFieldEnd();
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("ModisPixelLocation(");
    boolean first = true;

    sb.append("resolution:");
    if (this.resolution == null) {
      sb.append("null");
    } else {
      sb.append(this.resolution);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("tileH:");
    sb.append(this.tileH);
    first = false;
    if (!first) sb.append(", ");
    sb.append("tileV:");
    sb.append(this.tileV);
    first = false;
    if (!first) sb.append(", ");
    sb.append("sample:");
    sb.append(this.sample);
    first = false;
    if (!first) sb.append(", ");
    sb.append("line:");
    sb.append(this.line);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bit_vector = new BitSet(1);
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

}

